### ISSUE TITLE
Comp example file missing

### ISSUE THREAD

**Issue by matthiaskoenig** [shalinshah1993/SBSCL#27]
@shalinshah1993 Can you put the comp file with which you tested your comp code in
 `/src/test/resources/comp/`?

I cannot find this anywhere in the repository.

**Comment by shalinshah1993** [comment]
I used CompExample.java as a test file for hierarchical models. I think you moved that file to `src/main/java/` folder when you moved examples folder from test to main. Currently, this is where the file resides:

https://github.com/shalinshah1993/SBSCL/tree/working-branch/src/main/java/org/simulator/examples

You want me to move it or leave it for now since other test files that I used are all in the examples folder? I think we decided to work on them for now and then later move them to `src/test/java`.

**Comment by matthiaskoenig** [comment]
@shalinshah1993 I need the model you use. Can you upload the SBML comp model. Test and example code is clear.

**Comment by shalinshah1993** [comment]
Good point! I used all the test files found here in the comp jsbml commit: https://github.com/sbmlteam/jsbml/commit/46ca561edbca85a1f05f14dcc6e08acd65b2e235 

I don't think we want to push all the test files. Maybe we can add test 1 and test 2?

**Comment by shalinshah1993** [comment]
This issue was moved to draeger-lab/SBSCL#25
