### ISSUE TITLE
Add support for SteadyState simulation

### ISSUE THREAD

**Issue by shalinshah1993** [shalinshah1993/SBSCL#9]
SED-ML L1V2 added support for OneStep simulation elements and SteadyState. SBSCL currently runs UniformTimeCourse and OneStep. Support for SteadyState simulation needs to be added.

https://github.com/shalinshah1993/SBSCL/commit/d3656077437c6bf0efdf224a66b6fd35f0af802e

**Comment by shalinshah1993** [comment]
@draeger I remember you mentioned `FastProcesses` in our last meeting saying that it has something to do with `SteadyState`. Can you elaborate more here?

**Comment by draeger** [comment]
SBSCL's approach to solving fast reactions in a dynamic simulation is based on the fact that these quickly reach a steady state, i.e., a situation in which the concentrations of their reaction participants do no longer change. SBML files with fast reactions are here solved as follows. In every time step:
1. Solve the fast reactions until participants become constant, i.e., steady-state is reached.
2. Solve the entire reaction system from there.
3. Move to the next time step as usual.

In this sense, the `FastProcesses` interface is related to steady-state analysis because there we also have to find a situation in which the concentrations of the participants does no longer change.

Please note, however, that the approach described here for solving fast reactions is comparably inefficient. There are mathematically more involved but more efficient ways of doing it.

**Comment by shalinshah1993** [comment]
Okay, so they try to find `steadyState` so that overall solver is faster since computing is not required once `SteadyState` is reached. However, this routing still needs endTime. SED-ML doesn't supply any inputs to solver when it asks for `steadyState` simulation so we have to find the end time. 

A naive way is to solve for `t` and check if `steadyState` is reached or not and keep doing this until it is reached.

**Comment by draeger** [comment]
It seems the approach is not yet entirely clear. There is also no known end time when fast reactions reach a steady state (if ever, that is the hope). So, step 1 is executed until there is no change in those species that participate in fast reactions. This repeted simulation of fast reactions happens during a dynamic simulation of a system that contains reactions with attribute `fast=true` and possibly others with `fast=false`.

**Comment by shalinshah1993** [comment]
Okay, so what would the suggested way to approach this be for now?

I had a simple idea. We can run `oneStep` and generate output state which can be compared to current state. If the difference is not less than epsilon again do `oneStep`. The key is to increase step size logarithmically so we quickly reach `steadyState` (in a few iterations). Once we roughly know end time we can run `UniformTimeCourse` up to that time.

**Comment by draeger** [comment]
I assume that would work. Let's see if @matthiaskoenig agrees, too.

**Comment by shalinshah1993** [comment]
Added support for `SteadyState` with some default values. Closing this issue!
https://github.com/shalinshah1993/SBSCL/commit/59b98408c3fb270a28dcc87fb017206a4e10a6e0

**Comment by matthiaskoenig** [comment]
Example with test file missing demonstrating the feature. 
@shalinshah1993 please add a minimal example with test file, so we can test that this is working.

**Comment by shalinshah1993** [comment]
Check this commit - https://github.com/shalinshah1993/SBSCL/commit/a3b20122f8ce932b8c2c5e5f8355618abc72c7a0

**Comment by matthiaskoenig** [comment]
@shalinshah1993 This does not make sense. A steady state simulation is a simulation which will give you only one solution row (the steady state). 
Also it does not need any start and end values for the calculation. 

Instead of something like:
```
MultiTable solution = solver.solve(interpreter, interpreter.getInitialValues(), 0d, timeEnd);
```
There should be a method signature
```
MultiTable solution = solver.steadystate(interpreter, interpreter.getInitialValues());
```
I.e. time course solving and steady states are different things and they should not be mixed within one method.

**Comment by shalinshah1993** [comment]
Yes, line #60 is for UniformTimeCourse simulation. I just added comments after it so line #65 is what you need to uncomment for running steadyState simulation. It only needs initial values and the total number of steps you want as output.

**Comment by matthiaskoenig** [comment]
There were some bugs in the steady state calculation. For instance you have to add up the times of all the steps you are trying to know the time when you reached steady state. Also warning was missing if steady state cannot be reached.

I did the renaming so that it is clear that function calculates steadystate.

Also test cases are now added for steady state.
